name: Build

on:
    pull_request:
        branches:
            - main

    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./MultiGameApp

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "10.0.x"

            - name: Build
              run: dotnet build
